version: "3"
services:
  healthcheck1:
    restart: always
    ports:
      - ${PORT1}:${PORT1}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT1}
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
  healthcheck2:
    restart: always
    ports:
      - ${PORT2}:${PORT2}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT2}
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    image: fluent/fluentd:latest
    user: root
    ports:
      - 24224:24224
    volumes:
      - /var/lib/docker/containers:/fluentd/log/containers
      - ./fluent:/fluentd/etc/
      - ./logs:/output/
