version: '3'
services:
  healthcheck1:
    restart: always
    ports:
      - ${PORT1}:${PORT1}
    build: 
       context: .
       dockerfile: Dockerfile
       args:
         - PORT=${PORT1}
  healthcheck2:
    restart: always
    ports:
      - ${PORT2}:${PORT2}
    build: 
       context: .
       dockerfile: Dockerfile
       args:
         - PORT=${PORT2}
  fluentd:
     image: fluent/fluentd:latest
     user: root
     ports:
       - 24224:24224
     volumes:
       - /var/lib/docker/containers:/fluentd/log/containers
       - ./fluent:/fluentd/etc/
       - ./logs:/output/
